### ISSUE TITLE
Youtube Iframes not showing inside app

### ISSUE THREAD

**Issue by shaulhadar** [scottopolis/wpIonic#1]
Hi, thanks for this great project!!
I tested it and it works great, but for some reason, I can't see youtube videos which are embeded in my posts.  all the other elements are shown..

please let me know if there is anyway to fix this?

THanks :)

**Comment by scottopolis** [comment]
Hi, in your youtube embed code, does the iframe src use http or https? If the url is protocol-relative it won't work. For example src="//youtube.com/video"  You need to change it to src="https://youtube.com/video"

**Comment by shaulhadar** [comment]
Hi Scott, thanks for getting back to me.

my iframe code is something like this:

<iframe src="http://www.youtube.com/embed/iXtYE6x0Mok" width="100%" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

it has the http:// before the url.... and it looks good on desktop also.....

**Comment by scottopolis** [comment]
Just pushed a fix for this.

**Comment by shaulhadar** [comment]
Thanks Scott :)
