### ISSUE TITLE
Images are not adjusted according to screensize

### ISSUE THREAD

**Issue by rajesh-h** [scottopolis/wpIonic#11]
Hi First of all thanks for this nice code. 

I observed when I click on a post it's images are shown with actual size which is bigger than the mobile screen size. 

Am I supposed to change anything on the code? 

Thank you. 

Website I am using is cookingshooking.com

**Comment by scottopolis** [comment]
You may need to add `img { display:block; max-width:100%; }` or something similar to the CSS if your images are overflowing.

**Comment by rajesh-h** [comment]
Thank you, this has been resolved now. Images are shown properly now.

Have another issue where I need to activate authentication.
I went through this https://apppresser.com/custom-wp-api-authentication/ 

As i have activated reactor it also activated jason rest api (Wp API). Now in the blog post its said to include the plugin and there are two codes , I have put the second code in my Functions.php file. Please correct me am I doing something wrong?

**Comment by scottopolis** [comment]
You can use basic authentication: http://scottbolinger.com/wp-api-angular-basic-authentication/
