### ISSUE TITLE
Titles display &#8217; and &#8220;

### ISSUE THREAD

**Issue by sunylyons** [scottopolis/wpIonic#13]
Scott,

We're seeing an issue where titles display characters such as " and ' as ![untitled1](https://cloud.githubusercontent.com/assets/2180608/7906147/2ae1c286-07f3-11e5-9c29-b20ea8ae954a.png) and ![untitled 2](https://cloud.githubusercontent.com/assets/2180608/7906156/3e50f68e-07f3-11e5-9b0e-d6ff03c5e731.png)

The issue is only in post titles. Post content looks normal.

Does the correction of post content for these sorts of characters happen here? 
$scope.content = $sce.trustAsHtml(data.content);

And if so, how can I use something similar to target the post.title?

Cheers!

Cheers!

**Comment by scottopolis** [comment]
Hmm, you can try ng-bind-html="post.title" in the template and $scope.title = $sce.trustAsHtml(data.title) in the controller, although there's probably a better way to do it.

**Comment by sunylyons** [comment]
Thanks, yes we resolved by doing this for the list view:

$scope.title = $sce.trustAsHtml(data.title); 

and this for the detail view, after adding $sce to the controller function:

$scope.posts = $sce.trustAsHtml(data);
$scope.title = $sce.trustAsHtml(data.title);

along with ng-bind-html="post.title" in the template. I don't know if there's a better way but this certainly works! Cheers

**Comment by scottopolis** [comment]
Great, glad you got it figured out.
