### ISSUE TITLE
REST API not working in android

### ISSUE THREAD

**Issue by ghost** [scottopolis/wpIonic#15]
Hi Scott,

Loved it, but unfortunately if I compile and run in android device, the REST API is not working, do you have any idea why?

My device is ASUS Fonepad with Android 4.4 though...

**Comment by scottopolis** [comment]
There are no known issues with Android and the REST API, it's more likely that your project is setup incorrectly.

**Comment by svnlabs** [comment]
In Android device ... I checked using Developer Option > USB debugging ... it giving error

XMLHttpRequest cannot load file:///D:/ionic/wpIonic/www/templates/settings.html. 
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

What is solution for it?

**Comment by skating507** [comment]
have  the  same  problem

**Comment by scottopolis** [comment]
I'm seeing this too, there seems to be a 404 using a valid API url. I have no idea why, I may just rewrite the posts service.

**Comment by skating507** [comment]
hope to solve this problem soon

**Comment by mariusmaxa** [comment]
I have the same problem

**Comment by mariusmaxa** [comment]
Hi Scott,
can you attach the apk file for this project ?

**Comment by kdcllc** [comment]
@scottopolis I have forked this project and i have version of it running on Android.

**Comment by scottopolis** [comment]
@kdcllc was there a specific bug causing the issue with android? Care to submit a PR?

**Comment by salvatorecapolupo** [comment]
Go into platforms/android, edit AndroidManifest.xml and make sure these lines are in:

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

This worked for me and assure app can access through WP API.
