### ISSUE TITLE
Display feature image

### ISSUE THREAD

**Issue by CirrusTech** [scottopolis/wpIonic#16]
Hi there.

Thanks for a great tutorial and a great starter app!

I see the featured image is being returned in the JSON, however it seems to just be an ID of some kind, how does one take that and actually create an IMG tag SRC?

I saw this line commented out, I removed the comments but it doesn't display an image:

<img ng-if="post.featured_image" ng-src="{{post._embedded['http://v2.wp-api.org/attachment'][0][$index].source_url}}" class="alignleft" />

Thanks a lot!

**Comment by rebelholic** [comment]
https://github.com/WP-API/WP-API/issues/1624

**Comment by scottopolis** [comment]
Right now you have to do a separate request to /media/[id] to get the featured image. This is an oversight IMO, hopefully they will change that.
