### ISSUE TITLE
If i do a pull to refresh for the posts, they load again but only 4 posts

### ISSUE THREAD

**Issue by shaulhadar** [scottopolis/wpIonic#2]
Hello Scott, I am working with your great app, and i found a possible problem.  when i do a pull to refresh in the posts page, it works, but after the refresh it shows for me only 4 posts, instead of all the ones that were before, and i try to refresh again, it shows only the 4 posts..

is there someway to edit this behavior?

Thanks,
Shaul.

**Comment by scottopolis** [comment]
Hi, I'm not seeing this issue. Can you do some more troubleshooting and give me more information?

**Comment by shaulhadar** [comment]
Hi Scott. I checked again, and tried again with my site, but when i do pull to refresh it again shows me only 4 posts..

Can you please check at your end with my url: www.shaulhadar.com
I tried a few times and couldn't find what is the problem..

Thanks :)

**Comment by scottopolis** [comment]
I'm not sure why this is happening, might have to do with post pagination. What do you have under Settings => Reading=>Blog pages show at most setting?

**Comment by shaulhadar** [comment]
Hi Scott, thanks man! that was on 4 posts, but now that i changed it it works great :)

Thank you so much for your help, and have a great day :)
