### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by pmaojo** [scottopolis/wpIonic#22]
Hi. Im testing this app with ion view and when I am at /posts and scroll, some posts more load, but if click one post and go back again to posts and scroll down, no more are loaded. only the first page.

**Comment by kingstakh** [comment]
Add
`paged=2;`
to 

```
  $scope.doRefresh = function() {

    $timeout( function() {

      $scope.loadPosts();
      paged = 2;
      //Stop the ion-refresher from spinning
      $scope.$broadcast('scroll.refreshComplete');

    }, 1000);

  }
```

But I have another issue, function loadMore called twice when scroll down. Every time load 2 page instead of 1 page, this log:

```
loadMore 2
loadMore 3
```

then:

```
loadMore 4
loadMore 5
```

**Comment by scottopolis** [comment]
This project has been rewritten, please try again. It should work fine now.
