### ISSUE TITLE
can't load image

### ISSUE THREAD

**Issue by bagustilas** [scottopolis/wpIonic#25]
`<ion-view view-title="Posts">
  <ion-content>
  <ion-refresher on-refresh="doRefresh()"></ion-refresher>
    <ion-list>
        <ion-item  class="item item-thumbnail-left" class="item-icon-right" ng-repeat="post in posts track by $index" href="#/app/posts/{{post.id}}" track>
        <img ng-if="post.featured_image" ng-src="{{post._embedded['http://v2.wp-api.org/attachment'][0][$index].source_url}}" class="alignleft" />
            <h2 ng-bind-html="post.title.rendered"></h2>
            <p ng-if="post.excerpt.rendered" ng-bind-html="post.excerpt.rendered"></p>
            
        </ion-item>
    </ion-list>

```
<ion-infinite-scroll
ng-if="moreDataExists()"
on-infinite="loadMore()"
distance="1%"
immediate-check="false">
```

  </ion-infinite-scroll>

  </ion-content>
</ion-view>
`
can't load image

**Comment by scottopolis** [comment]
Please try again with the newest updates, thanks!
