### ISSUE TITLE
featured_image not showing

### ISSUE THREAD

**Issue by obzc** [scottopolis/wpIonic#26]
featured_image not showing.

**Comment by waheedsabir** [comment]
Hi Every one More people having the the error feature image 
Step1:Better REST API Featured Images download this plugin in your wordpress site 
Step2: use the `<img ng-src="{{post.better_featured_image.source_url}}" />`
for your feature image :)

**Comment by udha19** [comment]
i still got "better_featured_image": null, from postman, and of course on browser..
can you explain more detail?

**Comment by scottopolis** [comment]
Hi, please try again with the latest version, open a new issue if you still have trouble.
