### ISSUE TITLE
Help..

### ISSUE THREAD

**Issue by wubuyun** [scottopolis/wpIonic#34]
can someone help me to configure to access woocommerce, where I put consumer key and secret key, wordpress is ok.

**Comment by scottopolis** [comment]
Look at providers/woo/woo.ts line 65.  Base64 encode your key and secret and replace the authorization string.

"Basic auth requires base64 encoded string of 'Basic ' + btoa('key:secret')"

**Comment by wubuyun** [comment]
It would be like this
Basic ck_f0b2588129cb468165893e5d0a5b8214eb5dee8b:cs_2d6e7a3ac1edcfdb756b9dfcad9fd1c4fd4845ab

**Comment by wubuyun** [comment]
Basic Y2tfZjBiMjU4ODEyOWNiNDY4MTY1ODkzZTVkMGE1YjgyMTRlYjVkZWU4Yjpjc18yZDZlN2EzYWMxZWRjZmRiNzU2YjlkZmNhZDlmZDFjNGZkNDg0NWFi

**Comment by wubuyun** [comment]
not work too
