### ISSUE TITLE
Unclear guide

### ISSUE THREAD

**Issue by kevin25** [scottopolis/wpIonic#36]
Can you please give me an example of this?

> In the app, go to providers/woo/woo.ts and change the Authorization header. This is a base64 encoded string of your consumer key and secret. You can generate these using btoa(key:secret), but keep in mind these are discoverable in your app files even in a signed native app package.

Thank you

**Comment by scottopolis** [comment]
This got moved to configure.ts. Download the newest version of this repo, then see the example in the readme: https://github.com/scottopolis/wpIonic
