### ISSUE TITLE
Limited variable products?

### ISSUE THREAD

**Issue by kevin25** [scottopolis/wpIonic#37]
1. I only saw 10 variants from the app. Can you please show them all?

2. I have size and color attribute, is there any way to make the separate?

3. The thumbnails are not full.

4. Can you implement the WooCommerce FB tracking in the future?

5. The site is dead at checkout. Shipping cost is incorrect.

<img width="544" alt="screen shot 2018-03-19 at 18 23 21" src="https://user-images.githubusercontent.com/2909982/37625575-d79a8cf8-2ba2-11e8-9c9d-72c3efe4cc20.png">
<img width="396" alt="screen shot 2018-03-19 at 18 24 20" src="https://user-images.githubusercontent.com/2909982/37625576-d7d2f1b0-2ba2-11e8-98a2-d33e136d8747.png">

**Comment by scottopolis** [comment]
I've just pushed an edit that should pull all variations, please update your providers/woo/woo.ts file with the latest revision.

I may add attribute separation in the future.

I'm not sure what thumbnails you are referring to, but you are welcome to fork this repo and make any changes you like.

Please provide more information about your shipping error in a new thread, with exact steps on how to repeat.
