### ISSUE TITLE
http://localhost:8100/#/post-list

### ISSUE THREAD

**Issue by wubuyun** [scottopolis/wpIonic#38]
Error: Uncaught (in promise): [object Object] at c (http://192.168.1.38:8100/build/polyfills.js:3:19752) at c (http://192.168.1.38:8100/build/polyfills.js:3:19461) at http://192.168.1.38:8100/build/polyfills.js:3:20233 at t.invokeTask (http://192.168.1.38:8100/build/polyfills.js:3:15660) at Object.onInvokeTask (http://192.168.1.38:8100/build/vendor.js:4973:33) at t.invokeTask (http://192.168.1.38:8100/build/polyfills.js:3:15581) at r.runTask (http://192.168.1.38:8100/build/polyfills.js:3:10834) at o (http://192.168.1.38:8100/build/polyfills.js:3:7894) at e.invokeTask [as invoke] (http://192.168.1.38:8100/build/polyfills.js:3:16823) at p (http://192.168.1.38:8100/build/polyfills.js:2:27648)

**Comment by scottopolis** [comment]
This gives me no context, so I cannot help. Please include as many details as possible.
