### ISSUE TITLE
IPv6 Connection issue on iOS Submission

### ISSUE THREAD

**Issue by shirospyro** [scottopolis/wpIonic#40]
Hi Scott, I have followed all of your steps, and tested my app on my side, using the 'Create NAT64' thingy on my iMAC, Im not facing any issue on grabbing the data from my wordpress site but Apple can't seem to load the data on their side and they said that it is something to do with the IPv6.

How can I solve this issue with your template?

**Comment by scottopolis** [comment]
IPv6 is a type of network connection that has to do with your web host, it has nothing to do with the app files. You’ll need to contact your web host.

**Comment by shirospyro** [comment]
Hi, the thing is the site supports IPv6. I already contacted the web host, they said that they already set the IPv6 for it. My site is http://www.brunei.events. Any other advice?

http://ipv6-test.com/validate.php

**Comment by scottopolis** [comment]
This might have something to do with specific endpoints, check out this thread: https://forum.ionicframework.com/t/app-store-requirements-starting-june-2016-ipv6/51359/17

As noted, it has nothing to do with this Github project as far as I can tell.
