### ISSUE TITLE
Failed To Post Order

### ISSUE THREAD

**Issue by kevin25** [scottopolis/wpIonic#41]
I saw this issue when placing order with Paypal: 

> XHR finished loading: POST "https://www.domainname.com/wp-json/wc/v2/orders".

I haven't tested with Stripe yet.
2. It doesn't work with custom shipping Like Table Rate Shipping for WooCommerce. Customer can still place order without shipping option. It should be required.

> https://codecanyon.net/item/table-rate-shipping-for-woocommerce/3796656?s_rank=3

<img width="378" alt="screen shot 2018-04-06 at 07 08 11" src="https://user-images.githubusercontent.com/2909982/38418208-7d7ecb10-3969-11e8-8f3a-7a7e39b32d12.png">

**Comment by scottopolis** [comment]
There is no current support for Paypal or custom shipping plugins like the one you mentioned, sorry.
