### ISSUE TITLE
'page' is declared but never used.

### ISSUE THREAD

**Issue by mahdicomp** [scottopolis/wpIonic#45]
/wpIonic-master/src/providers/posts/posts.ts, line: 23
            'page' is declared but never used.

      L22:  if( !page ) {
      L23:    let page = '1';

///////////////in command line error .please help

**Comment by scottopolis** [comment]
Fixed in https://github.com/scottopolis/wpIonic/commit/c5568d0a376d823bc7bad9239e95450da3506caf
