### ISSUE TITLE
Iframe Can't Be Swiped Over

### ISSUE THREAD

**Issue by shaulhadar** [scottopolis/wpIonic#7]
Hello Scott, I have found a bug, but it's not something with your project, it is in all ionic projects, so i am not sure how to fix this, but maybe you can help..

The problem is that elements in an iframe, for example, a youtube video, can't be swiped down or up , it does nothing, so it makes a problem when you have wordpress posts with a video, and you can't scroll down sometimes... did you notice this and is there any way to fix this?

Thanks for your time,
Shaul.

**Comment by scottopolis** [comment]
Hi, you may be able to find a solution here: https://github.com/driftyco/ionic/issues/1151

Closing this since it's not an issue with my project.
