### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by toekneetone** [scottopolis/wpIonic#8]
Is there an easy solution to add a splash screen to wpionic app replacing the intro slider so it was just splashscreen then posts?

Do I have to add the platforms for IOS and Android to do so?

**Comment by scottopolis** [comment]
Splashscreen is a Phonegap feature: http://docs.phonegap.com/en/4.0.0/config_ref_images.md.html
It can be used with Ionic like this: http://learn.ionicframework.com/formulas/splash-screen/
