### ISSUE TITLE
Map Listings

### ISSUE THREAD

**Issue by toekneetone** [scottopolis/wpIonic#9]
Scott, So I am currently using this themehttp://preview.ait-themes.com/businessfinder/wp1/ that has a Map Pin Listing plugin integrated within the template that uses Google Maps API. Basically each individual pin on the map is a Custom post type and within the back end item/post you input address/longitude latitude. I have got my Ionic app the call the custom post type and would love to know if is possible to use the similar map pin feature. Any thoughts or feedback you could give me would be so helpful.

**Comment by scottopolis** [comment]
You would have to rebuild the map in Ionic using the Google Maps API, similar to what we did with Reactor: http://reactor.apppresser.com/
